from django.urls import path
from . import views

urlpatterns = [
	path('/home',views.home),
	path('/admin_login',views.admin_login),	
	path('/admin_login_data',views.admin_login_data),
	path('/admin_home',views.admin_home),
	path('/admin_doctor_home',views.admin_doctor_home),
	path('/admin_add_doctor',views.admin_add_doctor),
	path('/admin_add_doctor_data',views.admin_add_doctor_data),
	path('/admin_update_doctor',views.admin_update_doctor),
	path('/admin_update_doctor_success',views.admin_update_doctor_success),
	path('/admin_doctor_record',views.admin_doctor_record),
	path('/admin_patient_home',views.admin_patient_home),
	path('/admin_add_patient',views.admin_add_patient),
	path('/admin_add_patient_data',views.admin_add_patient_data),
	path('/admin_remove_patient',views.admin_remove_patient),
	path('/admin_remove_patient_success',views.admin_remove_patient_success),
	path('/admin_patient_record',views.admin_patient_record),
	path('/admin_logout',views.admin_logout),
	path('/admin_doctor_logout',views.admin_doctor_logout),
	path('/admin_patient_logout',views.admin_patient_logout),
	path('/doctor_login',views.doctor_login),
	path('/doctor_forget_password',views.doctor_forget_password),
	path('/doctor_change_password',views.doctor_change_password),
	path('/doctor_register',views.doctor_register),
	path('/doctor_reg_data',views.doctor_reg_data),
	path('/doctor_login_data',views.doctor_login_data),
	path('/doctor_home',views.doctor_home),
	path('/doctor_logout',views.doctor_logout),
	path('/patient_login',views.patient_login),
	path('/patient_forgot_password',views.patient_forgot_password),
	path('/patient_change_password',views.patient_change_password),
	path('/patient_register',views.patient_register),
	path('/patient_login_data',views.patient_login_data),
	path('/patient_reg_data',views.patient_reg_data),
	path('/patient_home',views.patient_home),
	path('/patient_book_appointment',views.patient_book_appointment),
	path('/patient_logout',views.patient_logout),
	path('/contact',views.contact)
]
